# Generated by Django 3.1.5 on 2021-06-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_auto_20210629_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agoratokenlog',
            name='creator',
            field=models.CharField(max_length=265),
        ),
    ]
