# Generated by Django 3.1.5 on 2021-06-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reported_users',
            options={'verbose_name': 'Reported Users', 'verbose_name_plural': 'Reported Users'},
        ),
        migrations.AlterField(
            model_name='reported_users',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
