# Generated by Django 3.1.5 on 2021-06-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20210625_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reported_users',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
