# Generated by Django 3.1.5 on 2021-06-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='age',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
            ],
            options={
                'verbose_name': 'age',
                'verbose_name_plural': 'age',
            },
        ),
        migrations.CreateModel(
            name='ethnicity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ethnicity', models.CharField(max_length=265)),
                ('ethnicity_fr', models.CharField(max_length=265)),
            ],
            options={
                'verbose_name': 'ethinicty',
                'verbose_name_plural': 'ethinicty',
            },
        ),
        migrations.CreateModel(
            name='family',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('familyPlans', models.CharField(max_length=265)),
                ('familyPlans_fr', models.CharField(max_length=265)),
            ],
            options={
                'verbose_name': 'family',
                'verbose_name_plural': 'family',
            },
        ),
    ]
