# Generated by Django 3.1.5 on 2021-06-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaultPicker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='politics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('politics', models.CharField(max_length=265)),
                ('politics_fr', models.CharField(max_length=265)),
            ],
            options={
                'verbose_name': 'politics',
                'verbose_name_plural': 'politics',
            },
        ),
        migrations.CreateModel(
            name='religious',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('religious', models.CharField(max_length=265)),
                ('religious_fr', models.CharField(max_length=265)),
            ],
            options={
                'verbose_name': 'religious',
                'verbose_name_plural': 'religious',
            },
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=265)),
                ('tag_fr', models.CharField(max_length=265)),
            ],
            options={
                'verbose_name': 'tags',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='zodiacSign',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zodiacSign', models.CharField(max_length=265)),
                ('zodiacSign_fr', models.CharField(max_length=265)),
            ],
            options={
                'verbose_name': 'zodiacSign',
                'verbose_name_plural': 'zodiacSign',
            },
        ),
    ]
