# Generated by Django 3.1.5 on 2021-07-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaultPicker', '0002_politics_religious_tags_zodiacsign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethnicity',
            name='ethnicity_fr',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='familyPlans_fr',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AlterField(
            model_name='politics',
            name='politics_fr',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AlterField(
            model_name='religious',
            name='religious_fr',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag_fr',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AlterField(
            model_name='zodiacsign',
            name='zodiacSign_fr',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
    ]
