# Generated by Django 3.1.5 on 2021-07-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaultPicker', '0003_auto_20210712_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='age',
            name='age_fr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
