# Generated by Django 3.1.5 on 2021-06-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210629_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveBigIntegerField(blank=True, choices=[(0, '18'), (1, '19'), (2, '20'), (3, '21'), (4, '22'), (5, '23'), (6, '24'), (7, '25'), (8, '26'), (9, '27'), (10, '28'), (11, '29'), (12, '30'), (13, '31'), (14, '32'), (15, '33'), (16, '34'), (17, '35'), (18, '36'), (19, '37'), (20, '38'), (21, '39'), (22, '40'), (23, '41'), (24, '42'), (25, '43'), (26, '44'), (27, '45'), (28, '46'), (29, '47'), (30, '48'), (31, '49'), (32, '50'), (33, '51'), (34, '52'), (35, '53'), (36, '54'), (37, '55'), (38, '56'), (39, '57'), (40, '58'), (41, '59')], null=True),
        ),
    ]
