# Generated by Django 3.1.5 on 2021-06-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210629_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
