# Generated by Django 3.1.5 on 2021-07-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210711_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=70)),
                ('coins_needed', models.IntegerField()),
            ],
        ),
    ]
