# Generated by Django 3.1.5 on 2021-07-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_coinsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='profile_tags', to='user.Tags'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zodiacSign',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
